# Generated by Django 4.0.5 on 2022-06-03 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmnuser',
            old_name='activated',
            new_name='is_activated',
        ),
    ]
