# Generated by Django 4.0.5 on 2022-06-04 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_activated_cmnuser_is_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Name')),
                ('order', models.SmallIntegerField(db_index=True, default=0, verbose_name='Order')),
            ],
        ),
        migrations.CreateModel(
            name='SubHeading',
            fields=[
            ],
            options={
                'verbose_name': 'Subheading',
                'verbose_name_plural': 'Subheadings',
                'ordering': ('super_heading__order', 'super_heading__name', 'order', 'name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.heading',),
        ),
        migrations.CreateModel(
            name='SuperHeading',
            fields=[
            ],
            options={
                'verbose_name': 'Main Heading',
                'verbose_name_plural': 'Main Headings',
                'ordering': ('order', 'name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.heading',),
        ),
        migrations.AddField(
            model_name='heading',
            name='super_heading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.superheading', verbose_name='Main Heading'),
        ),
    ]
