# Generated by Django 4.0.5 on 2022-06-10 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор об`яви'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='contacts',
            field=models.TextField(verbose_name='Контакти'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='content',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, upload_to=main.utilities.get_time_marker, verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.FloatField(default=0, verbose_name='Ціна'),
        ),
    ]
